"""
Trains the SlopeGuard prototype landslide-risk model.

IMPORTANT: This trains on SYNTHETIC data generated by a hand-authored rule
+ noise, because no licensed ground-truth landslide dataset is bundled with
this prototype. The resulting model is suitable for demonstrating the full
architecture (feature pipeline -> XGBoost -> explainable score -> API) but
must NOT be presented as a scientifically validated predictor. Swap
`generate_synthetic_dataset()` for a real ingestion pipeline (ISRO / Bhuvan /
GEE / historical landslide inventories) before any operational use.

Run:
    python -m backend.ml.training.train
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
)

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from ml.features import FEATURES, risk_level_for_score  # noqa: E402

MODEL_DIR = Path(__file__).resolve().parents[1] / "model"
MODEL_DIR.mkdir(exist_ok=True)

N_SAMPLES = 6000
RANDOM_SEED = 42


def generate_synthetic_dataset(n=N_SAMPLES, seed=RANDOM_SEED) -> pd.DataFrame:
    rng = np.random.default_rng(seed)

    rainfall_24h = rng.beta(2, 3, n) * 100
    rainfall_cumulative = np.clip(rainfall_24h * 0.6 + rng.normal(0, 12, n), 0, 100)
    soil_moisture = np.clip(rainfall_cumulative * 0.5 + rng.normal(40, 15, n), 0, 100)
    slope = rng.beta(2, 2.2, n) * 100
    elevation = rng.uniform(0, 100, n)
    ndvi = np.clip(100 - slope * 0.3 + rng.normal(50, 20, n), 0, 100)
    distance_to_road = rng.uniform(0, 100, n)
    historical_landslide_density = np.clip(
        slope * 0.3 + rainfall_cumulative * 0.2 + rng.normal(20, 20, n), 0, 100
    )
    temperature = rng.uniform(8, 34, n)

    df = pd.DataFrame({
        "rainfall_24h": rainfall_24h,
        "rainfall_cumulative": rainfall_cumulative,
        "soil_moisture": soil_moisture,
        "slope": slope,
        "elevation": elevation,
        "ndvi": ndvi,
        "distance_to_road": distance_to_road,
        "historical_landslide_density": historical_landslide_density,
        "temperature": temperature,
    })

    # Ground-truth generating function: a weighted combination reflecting
    # widely documented landslide-conditioning factors (rainfall, saturated
    # soil, steep slope, sparse vegetation, proximity to cut slopes/roads,
    # historical susceptibility), plus noise, clipped to 0-100. This is the
    # SYNTHETIC label the model learns to reproduce.
    veg_risk = 100 - df["ndvi"]
    road_risk = 100 - df["distance_to_road"]
    raw = (
        0.22 * df["rainfall_24h"]
        + 0.15 * df["rainfall_cumulative"]
        + 0.18 * df["soil_moisture"]
        + 0.20 * df["slope"]
        + 0.05 * df["elevation"]
        + 0.08 * veg_risk
        + 0.05 * road_risk
        + 0.07 * df["historical_landslide_density"]
    )
    noise = rng.normal(0, 6, n)
    df["risk_score"] = np.clip(raw + noise, 0, 100)
    df["risk_level"] = df["risk_score"].apply(risk_level_for_score)
    return df


def train():
    df = generate_synthetic_dataset()
    X = df[FEATURES]
    y_reg = df["risk_score"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_reg, test_size=0.2, random_state=RANDOM_SEED
    )

    model = xgb.XGBRegressor(
        n_estimators=250,
        max_depth=5,
        learning_rate=0.06,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_lambda=1.0,
        objective="reg:squarederror",
        random_state=RANDOM_SEED,
    )
    model.fit(X_train, y_train)

    # Evaluate as regression + derived classification (LOW/MOD/HIGH/VERY_HIGH)
    pred_test = np.clip(model.predict(X_test), 0, 100)
    true_level = y_test.apply(risk_level_for_score)
    pred_level = pd.Series(pred_test, index=y_test.index).apply(risk_level_for_score)

    # Binary "elevated risk" (HIGH or VERY_HIGH) view for precision/recall/AUC
    true_bin = true_level.isin(["HIGH", "VERY_HIGH"]).astype(int)
    pred_bin = pred_level.isin(["HIGH", "VERY_HIGH"]).astype(int)
    pred_score_norm = pred_test / 100.0

    metrics = {
        "accuracy": round(accuracy_score(true_level, pred_level), 4),
        "precision": round(precision_score(true_bin, pred_bin, zero_division=0), 4),
        "recall": round(recall_score(true_bin, pred_bin, zero_division=0), 4),
        "f1_score": round(f1_score(true_bin, pred_bin, zero_division=0), 4),
        "roc_auc": round(roc_auc_score(true_bin, pred_score_norm), 4),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "trained_on": "synthetic_v1",
        "note": "Computed on a synthetic hold-out split for architecture "
                "demonstration only. Not a validated real-world accuracy figure.",
    }

    model_path = MODEL_DIR / "landslide_xgb_v1.json"
    model.save_model(model_path)

    meta = {
        "model_version": "v1.0.0-prototype",
        "algorithm": "XGBoost Regressor",
        "features": FEATURES,
        "trained_on": "synthetic",
        "metrics": metrics,
    }
    with open(MODEL_DIR / "model_meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(json.dumps(meta, indent=2))
    return meta


if __name__ == "__main__":
    train()
